services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app_network
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=2592
    networks:
      - app_network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  mysql-data: